# SPDX-FileCopyrightText: Copyright 2022-2025 Arm Limited and/or its
# affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Build TG2 Release
on:

  workflow_dispatch:
  #pull_request:
  #  branches: [main]
  #push:
  #  branches: [main]
  #schedule:
  #  - cron: '00 20 * * 6'

  
jobs:
  CI:
    strategy:
      max-parallel: 1
      matrix:
        context: [
          { tool: AC6,  dir: ./App,  proj: TG2,  target_type: T2G-Kit,  build_type: Release,  cbld_set: Release}
          ]
      fail-fast: false

    runs-on: self-hosted

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Activate vcpkg
      uses: ARM-software/cmsis-actions/vcpkg@v1
      with:
        config: "./vcpkg-configuration.json"
        cache: ""

    - name: Activate Arm tool license
      uses: ARM-software/cmsis-actions/armlm@v1

    - name: Run cbuild setup for ${{matrix.context.tool}}_${{matrix.context.proj}}.csolution.yml
      working-directory: ${{matrix.context.dir}}
      run: |
        cbuild setup ${{matrix.context.proj}}.csolution.yml --active ${{matrix.context.target_type}}@${{matrix.context.cbld_set}} --packs

    - name: ${{matrix.context.tool}} Build-Test for context ${{matrix.context.proj}}.${{matrix.context.build_type}}+${{matrix.context.target_type}}
      working-directory: ${{matrix.context.dir}}
      run: |
        cbuild ${{matrix.context.proj}}.csolution.yml --context .${{matrix.context.build_type}}+${{matrix.context.target_type}} --toolchain ${{matrix.context.tool}} --packs

    - name: Upload output for context ${{matrix.context.proj}}.${{matrix.context.build_type}}+${{matrix.context.target_type}}
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.context.tool}}_build_${{matrix.context.proj}}.${{matrix.context.build_type}}+${{matrix.context.target_type}}
        path: ${{matrix.context.dir}}/out

